import TOS from '../../src/browser-index';
import downloadFile from '../../src/methods/object/downloadFile';
import { deleteBucket, NEVER_TIMEOUT, sleepCache } from '../utils';
import {
  isNeedDeleteBucket,
  testBucketName,
  tosOptions,
} from '../utils/options';
import {
  initAutoGeneratedObjects,
  objectKey10M,
  objectKey1M,
  objectPath10M,
  objectPath1K,
  objectPath1M,
} from './utils';
initAutoGeneratedObjects();
describe('test crc64', () => {
  beforeAll(async (done) => {
    const client = new TOS(tosOptions);
    // clear all bucket
    const { data: buckets } = await client.listBuckets();
    for (const bucket of buckets.Buckets) {
      if (isNeedDeleteBucket(bucket.Name)) {
        try {
          await deleteBucket(client, bucket.Name);
        } catch (err) {
          console.log('a: ', err);
        }
      }
    }
    // create bucket
    await client.createBucket({
      bucket: testBucketName,
    });
    await sleepCache();
    done();
  }, NEVER_TIMEOUT);
  // afterAll(async done => {
  //   const client = new TOS(tosOptions);
  //   console.log('delete bucket.....');
  //   // delete bucket
  //   deleteBucket(client, testBucketName);
  //   done();
  // }, NEVER_TIMEOUT);

  it('case 1', async () => {});

  it(
    'putObject with crc',
    async () => {
      const key = `${objectKey10M}-put-with-crc`;
      const client = new TOS({ ...tosOptions, enableCRC: true });

      await client.putObjectFromFile({
        filePath: objectPath10M,
        key,
      });

      const { data } = await client.headObject(key);
      expect(+data['content-length'] === 10 * 1024 * 1024).toBeTruthy();
    },
    NEVER_TIMEOUT
  );

  it(
    'uploadFile with crc',
    async () => {
      const key = `${objectKey10M}-uploadFile-with-crc`;
      const client = new TOS({ ...tosOptions, enableCRC: true });

      await client.uploadFile({
        file: objectPath10M,
        key,
      });

      const { data } = await client.headObject(key);
      expect(+data['content-length'] === 10 * 1024 * 1024).toBeTruthy();
    },
    NEVER_TIMEOUT
  );

  it(
    'downLoadFile with crc',
    async () => {
      const key = `${objectPath1M}-put-with-crc`;
      const client = new TOS({ ...tosOptions });

      await client.putObjectFromFile({
        filePath: objectPath1M,
        key,
      });

      const downloadClient = new TOS({ ...tosOptions, enableCRC: true });

      await downloadClient.downloadFile({
        key,
        filePath: './test/node/tmp/downloadFile/',
        partSize: 100 * 1024,
      });

      const { data } = await client.headObject(key);
      expect(+data['content-length'] === 1 * 1024 * 1024).toBeTruthy();
    },
    NEVER_TIMEOUT
  );
});
