import TOS from '../../src/browser-index';
import { getEndpoint } from '../../src/utils';
import { NEVER_TIMEOUT, deleteBucket } from '../utils';
import {
  isNeedDeleteBucket,
  testBucketName,
  tosOptions,
} from '../utils/options';
import { initAutoGeneratedObjects, objectKey1K, objectPath1K } from './utils';

const key = `getObject-${objectKey1K}`;

initAutoGeneratedObjects();

describe('customDomain test environment', () => {
  beforeAll(async (done) => {
    const client = new TOS(tosOptions);
    // clear all bucket
    const { data: buckets } = await client.listBuckets();
    for (const bucket of buckets.Buckets) {
      if (isNeedDeleteBucket(bucket.Name)) {
        try {
          await deleteBucket(client, bucket.Name);
        } catch (err) {
          console.log('a: ', err);
        }
      }
    }
    // create bucket
    await client.createBucket({
      bucket: testBucketName,
    });

    await client.putObjectFromFile({
      key,
      filePath: objectPath1K,
    });

    done();
  }, NEVER_TIMEOUT);

  it(
    'headObject by default',
    async () => {
      const client = new TOS(tosOptions);

      const res = await client.headObject({
        key,
      });

      expect(+res.data['content-length']).toBe(1024);
    },
    NEVER_TIMEOUT
  );

  it(
    'headObject by CustomDomain without bucket',
    async () => {
      const client = new TOS({ ...tosOptions, isCustomDomain: true });
      let errCount = 0;
      let successCount = 0;
      try {
        const res = await client.headObject({
          key,
        });
        successCount++;
      } catch (error) {
        errCount++;
      }
      expect(errCount).toBe(1);
      expect(successCount).toBe(0);
    },
    NEVER_TIMEOUT
  );

  it(
    'headObject CustomDomain with bucket prefix',
    async () => {
      const client = new TOS({
        ...tosOptions,
        isCustomDomain: true,
        endpoint: `${testBucketName}.${getEndpoint(tosOptions.region)}`,
      });

      const res = await client.headObject({
        key,
      });

      expect(+res.data['content-length']).toBe(1024);
    },
    NEVER_TIMEOUT
  );
});
