import {
  initCheckpointsDir,
  initDownloadFileDir,
  initAutoGeneratedObjects,
} from './utils';
import { createAllTestBuckets } from '../utils/createAllTestBuckets';

module.exports = async function () {
  initAutoGeneratedObjects();
  initCheckpointsDir();
  initDownloadFileDir();
  await createAllTestBuckets();
};
